# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-devlinux-communication"
BBFILE_PATTERN_meta-devlinux-communication = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-devlinux-communication = "6"

LAYERDEPENDS_meta-devlinux-communication = "core"
LAYERSERIES_COMPAT_meta-devlinux-communication = "kirkstone"

## Adding these to your layer's conf/layer.conf file
# MACHINE ??= "raspberrypi4"

# # Default Wi-Fi credentials consumed by the wifi-config recipe.
# # Replace with the SSID and passphrase for the access point you want the image to join.
# WIFI_SSID = "Nguyen Thanh Dat"
# WIFI_PSK = "0399433420"

# # Ensure Wi-Fi support is available to the image.
# DISTRO_FEATURES:append = " systemd wifi"
# VIRTUAL-RUNTIME_init_manager = "systemd"
# VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
# VIRTUAL-RUNTIME_init = "systemd"
# PREFERRED_PROVIDER_virtual/init = "systemd"

# IMAGE_INSTALL:remove = " sysvinit"
# RM_OLD_IMGAGES = "1"
# INHERIT += "extrausers rm_work"
# EXTRA_USERS_PARAMS = "groupadd netdev; "
